str1 = input("Enter first string: ")
str2 = input("Enter second string: ")
combined = str1 + str2

print("\n--- String Methods ---")
print("lower():", combined.lower())
print("upper():", combined.upper())
print("title():", combined.title())
print("swapcase():", combined.swapcase())
print("capitalize():", combined.capitalize())
print("casefold():", combined.casefold())
print("center(30):", combined.center(30))
print("count('a'):", combined.count('a'))
print("endswith('a'):", combined.endswith('a'))
print("find('a'):", combined.find('a'))
print("isalnum():", combined.isalnum())
print("isdigit():", combined.isdigit())
print("isnumeric():", combined.isnumeric())
print("isspace():", combined.isspace())
print("replace('a', '@'):", combined.replace('a', '@'))
